export type Match = {
  id: string;
  date: string;
  teamA: string;
  teamB: string;
  logoA: string;
  logoB: string;
};

const flagBaseUrl = "https://flagcdn.com/48x36/";

export const matchesFirstMatchDay: Match[] = [
  {
    id: "1",
    date: "14.06.24 21:00",
    teamA: "Germany",
    teamB: "Scotland",
    logoA: `${flagBaseUrl}de.png`,
    logoB: `${flagBaseUrl}gb-sct.png`,
  },
  {
    id: "2",
    date: "15.06.24 15:00",
    teamA: "Hungary",
    teamB: "Switzerland",
    logoA: `${flagBaseUrl}hu.png`,
    logoB: `${flagBaseUrl}ch.png`,
  },
  {
    id: "3",
    date: "15.06.24 18:00",
    teamA: "Spain",
    teamB: "Croatia",
    logoA: `${flagBaseUrl}es.png`,
    logoB: `${flagBaseUrl}hr.png`,
  },
  {
    id: "4",
    date: "15.06.24 21:00",
    teamA: "Italy",
    teamB: "Albania",
    logoA: `${flagBaseUrl}it.png`,
    logoB: `${flagBaseUrl}al.png`,
  },
  {
    id: "5",
    date: "16.06.24 15:00",
    teamA: "Poland",
    teamB: "Netherlands",
    logoA: `${flagBaseUrl}pl.png`,
    logoB: `${flagBaseUrl}nl.png`,
  },
  {
    id: "6",
    date: "16.06.24 18:00",
    teamA: "Slovenia",
    teamB: "Denmark",
    logoA: `${flagBaseUrl}si.png`,
    logoB: `${flagBaseUrl}dk.png`,
  },
  {
    id: "7",
    date: "16.06.24 21:00",
    teamA: "Serbia",
    teamB: "England",
    logoA: `${flagBaseUrl}rs.png`,
    logoB: `${flagBaseUrl}gb-eng.png`,
  },
  {
    id: "8",
    date: "17.06.24 15:00",
    teamA: "Romania",
    teamB: "Ukraine",
    logoA: `${flagBaseUrl}ro.png`,
    logoB: `${flagBaseUrl}ua.png`,
  },
  {
    id: "9",
    date: "17.06.24 18:00",
    teamA: "Belgium",
    teamB: "Slovakia",
    logoA: `${flagBaseUrl}be.png`,
    logoB: `${flagBaseUrl}sk.png`,
  },
  {
    id: "10",
    date: "17.06.24 21:00",
    teamA: "Austria",
    teamB: "France",
    logoA: `${flagBaseUrl}at.png`,
    logoB: `${flagBaseUrl}fr.png`,
  },
  {
    id: "11",
    date: "18.06.24 18:00",
    teamA: "Türkiye",
    teamB: "Georgia",
    logoA: `${flagBaseUrl}tr.png`,
    logoB: `${flagBaseUrl}ge.png`,
  },
  {
    id: "12",
    date: "18.06.24 21:00",
    teamA: "Portugal",
    teamB: "Czechia",
    logoA: `${flagBaseUrl}pt.png`,
    logoB: `${flagBaseUrl}cz.png`,
  },
];

export const matchesSecondMatchday: Match[] = [
  {
    id: "13",
    date: "19.06.24 15:00",
    teamA: "Croatia",
    teamB: "Albania",
    logoA: `${flagBaseUrl}hr.png`,
    logoB: `${flagBaseUrl}al.png`,
  },
  {
    id: "14",
    date: "19.06.24 18:00",
    teamA: "Germany",
    teamB: "Hungary",
    logoA: `${flagBaseUrl}de.png`,
    logoB: `${flagBaseUrl}hu.png`,
  },
  {
    id: "15",
    date: "19.06.24 21:00",
    teamA: "Scotland",
    teamB: "Switzerland",
    logoA: `${flagBaseUrl}gb-sct.png`,
    logoB: `${flagBaseUrl}ch.png`,
  },
  {
    id: "16",
    date: "20.06.24 15:00",
    teamA: "Slovenia",
    teamB: "Serbia",
    logoA: `${flagBaseUrl}si.png`,
    logoB: `${flagBaseUrl}rs.png`,
  },
  {
    id: "17",
    date: "20.06.24 18:00",
    teamA: "Denmark",
    teamB: "England",
    logoA: `${flagBaseUrl}dk.png`,
    logoB: `${flagBaseUrl}gb-eng.png`,
  },
  {
    id: "18",
    date: "20.06.24 21:00",
    teamA: "Spain",
    teamB: "Italy",
    logoA: `${flagBaseUrl}es.png`,
    logoB: `${flagBaseUrl}it.png`,
  },
  {
    id: "19",
    date: "21.06.24 15:00",
    teamA: "Slovakia",
    teamB: "Ukraine",
    logoA: `${flagBaseUrl}sk.png`,
    logoB: `${flagBaseUrl}ua.png`,
  },
  {
    id: "20",
    date: "21.06.24 18:00",
    teamA: "Poland",
    teamB: "Austria",
    logoA: `${flagBaseUrl}pl.png`,
    logoB: `${flagBaseUrl}at.png`,
  },
  {
    id: "21",
    date: "21.06.24 21:00",
    teamA: "Netherland",
    teamB: "France",
    logoA: `${flagBaseUrl}nl.png`,
    logoB: `${flagBaseUrl}fr.png`,
  },
  {
    id: "22",
    date: "22.06.24 15:00",
    teamA: "Georgia",
    teamB: "Czechia",
    logoA: `${flagBaseUrl}ge.png`,
    logoB: `${flagBaseUrl}cz.png`,
  },
  {
    id: "23",
    date: "22.06.24 18:00",
    teamA: "Türkiye",
    teamB: "Portugal",
    logoA: `${flagBaseUrl}tr.png`,
    logoB: `${flagBaseUrl}pt.png`,
  },
  {
    id: "24",
    date: "22.06.24 21:00",
    teamA: "Belgium",
    teamB: "Romania",
    logoA: `${flagBaseUrl}be.png`,
    logoB: `${flagBaseUrl}ro.png`,
  },
];

export const matchesThirdMatchday: Match[] = [
  {
    id: "25",
    date: "23.06.24 21:00",
    teamA: "Switzerland",
    teamB: "Germany",
    logoA: `${flagBaseUrl}ch.png`,
    logoB: `${flagBaseUrl}de.png`,
  },
  {
    id: "26",
    date: "23.06.24 21:00",
    teamA: "Scotland",
    teamB: "Hungary",
    logoA: `${flagBaseUrl}gb-sct.png`,
    logoB: `${flagBaseUrl}hu.png`,
  },
  {
    id: "27",
    date: "24.06.24 21:00",
    teamA: "Albania",
    teamB: "Spain",
    logoA: `${flagBaseUrl}al.png`,
    logoB: `${flagBaseUrl}es.png`,
  },
  {
    id: "28",
    date: "24.06.24 21:00",
    teamA: "Croatia",
    teamB: "Italy",
    logoA: `${flagBaseUrl}hr.png`,
    logoB: `${flagBaseUrl}it.png`,
  },
  {
    id: "29",
    date: "25.06.24 18:00",
    teamA: "Netherlands",
    teamB: "Austria",
    logoA: `${flagBaseUrl}nl.png`,
    logoB: `${flagBaseUrl}at.png`,
  },
  {
    id: "30",
    date: "25.06.24 18:00",
    teamA: "France",
    teamB: "Poland",
    logoA: `${flagBaseUrl}fr.png`,
    logoB: `${flagBaseUrl}pl.png`,
  },
  {
    id: "31",
    date: "25.06.24 21:00",
    teamA: "England",
    teamB: "Slovenia",
    logoA: `${flagBaseUrl}gb-eng.png`,
    logoB: `${flagBaseUrl}si.png`,
  },
  {
    id: "32",
    date: "25.06.24 21:00",
    teamA: "Denmark",
    teamB: "Serbia",
    logoA: `${flagBaseUrl}dk.png`,
    logoB: `${flagBaseUrl}rs.png`,
  },
  {
    id: "33",
    date: "26.06.24 18:00",
    teamA: "Slovakia",
    teamB: "Romania",
    logoA: `${flagBaseUrl}sk.png`,
    logoB: `${flagBaseUrl}ro.png`,
  },
  {
    id: "34",
    date: "26.06.24 18:00",
    teamA: "Ukraine",
    teamB: "Belgium",
    logoA: `${flagBaseUrl}ua.png`,
    logoB: `${flagBaseUrl}be.png`,
  },
  {
    id: "35",
    date: "26.06.24 21:00",
    teamA: "Georgia",
    teamB: "Portugal",
    logoA: `${flagBaseUrl}ge.png`,
    logoB: `${flagBaseUrl}pt.png`,
  },
  {
    id: "36",
    date: "26.06.24 21:00",
    teamA: "Czechia",
    teamB: "Türkiye",
    logoA: `${flagBaseUrl}cz.png`,
    logoB: `${flagBaseUrl}tr.png`,
  },
];

export const matchesRound16: Match[] = [
  {
    id: "37",
    date: "29.06.24 18:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "38",
    date: "29.06.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "39",
    date: "30.06.24 18:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "40",
    date: "30.06.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "41",
    date: "01.07.24 18:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "42",
    date: "01.07.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "43",
    date: "02.07.24 18:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "44",
    date: "02.07.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
];
export const matchesQuarterFinals: Match[] = [
  {
    id: "45",
    date: "05.07.24 18:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "46",
    date: "05.07.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "47",
    date: "06.07.24 18:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "48",
    date: "07.07.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
];
export const matchesSemiFinals: Match[] = [
  {
    id: "49",
    date: "09.07.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
  {
    id: "50",
    date: "10.07.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
];
export const matchesFinal: Match[] = [
  {
    id: "51",
    date: "14.07.24 21:00",
    teamA: "tbd",
    teamB: "tbd",
    logoA: "",
    logoB: "",
  },
];

export const allMatches: Match[] = matchesFirstMatchDay.concat(
  matchesSecondMatchday,
  matchesThirdMatchday,
  matchesRound16,
  matchesQuarterFinals,
  matchesSemiFinals,
  matchesFinal
);
